# Generated by Django 4.2.5 on 2023-09-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_job_alter_blog_id_alter_students_id_jobstats_joblogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='html',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='recommended',
        ),
    ]
