# Generated by Django 4.1.3 on 2022-12-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_job_jobstats_joblogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='no_of_blogs_to_extract',
            new_name='no_of_blogs',
        ),
        migrations.AddField(
            model_name='job',
            name='start_no',
            field=models.IntegerField(null=True, verbose_name='No of blogs to skip'),
        ),
    ]
