# Generated by Django 4.1.3 on 2022-12-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_rename_no_of_blogs_to_extract_job_no_of_blogs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblogs',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Log date'),
        ),
    ]
