# Generated by Django 4.1.3 on 2022-12-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_joblogs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblogs',
            name='function_name',
            field=models.TextField(verbose_name='Function name'),
        ),
    ]
